apiVersion: v2
appVersion: latest
description: premiumizer
name: premiumizer
version: 0.9.0
kubeVersion: ">=1.16.0-0"
keywords:
- premiumizer
home: https://github.com/thelastguardian/helm-charts/tree/master/charts/premiumizer
sources:
- https://github.com/piejanssens/premiumizer
maintainers:
- name: thelastguardian
  email: me@thelastguardian.me
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 3.2.0