apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "premiumizer.fullname" . }}
  labels:
    {{- include "premiumizer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "premiumizer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "premiumizer.selectorLabels" . | nindent 8 }}
    spec:
      hostAliases:
      - ip: "88.99.115.46"
        hostnames:
        - "api.jdownloader.org"
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: "{{ .Values.timezone }}"
            - name: PUID
              value: "{{ .Values.puid }}"
            - name: PGID
              value: "{{ .Values.pgid }}"
          volumeMounts:
            - mountPath: /conf
              name: config
              {{- if .Values.persistence.config.subPath }}
              subPath: "{{ .Values.persistence.config.subPath }}"
              {{- end }}
            - mountPath: /downloads
              name: downloads
            {{- if .Values.persistence.downloads.subPath }}
              subPath: {{ .Values.persistence.downloads.subPath }}
            {{- end }}
            - mountPath: /blackhole
              name: blackhole
            {{- if .Values.persistence.blackhole.subPath }}
              subPath: {{ .Values.persistence.blackhole.subPath }}
            {{- end }}
            {{- range .Values.persistence.extraExistingClaimMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly }}
            {{- end }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: config
      {{- if .Values.persistence.config.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.config.existingClaim }}{{ .Values.persistence.config.existingClaim }}{{- else }}{{ template "premiumizer.fullname" . }}-config{{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: downloads
      {{- if .Values.persistence.downloads.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.downloads.existingClaim }}{{ .Values.persistence.downloads.existingClaim }}{{- else }}{{ template "premiumizer.fullname" . }}-downloads{{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: blackhole
      {{- if .Values.persistence.blackhole.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.blackhole.existingClaim }}{{ .Values.persistence.blackhole.existingClaim }}{{- else }}{{ template "premiumizer.fullname" . }}-blackhole{{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- range .Values.persistence.extraExistingClaimMounts }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ .existingClaim }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
